model:
  name: Base
  methods:
    get.translated.attributes:
      comment: Get the translated attributes
      returnType: array
      content:
        php-core: return $this->translatedAttributes();
        js-ember: return this.translatedAttributes();
compilers:
  - php-laravel
  # - js-ember
